apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kong-db-pvc
spec:
  accessModes:
    # Permite que el volumen sea montado como lectura/escritura por un único nodo.
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi