apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-pvc
  labels:
    app: kong-database
spec:
  accessModes:
    - ReadWriteOnce # Permite que un solo nodo monte el volumen como lectura/escritura
  resources:
    requests:
      storage: 10Gi # Solicita 10 Gigabytes de almacenamiento